const auth = require("./auth");
const user = require("./user");
const role = require("./role");
const groupRole = require("./groupRole");
const category = require("./category");
const brand = require("./brand");
const product = require("./product");
const variant = require("./variant");
const comment = require("./comment");
const discount = require("./discount");
const size = require("./size");
const color = require("./color");
const order = require("./order");
const cart = require("./cart");
const address = require("./address");
const rating = require("./rating");

const router = (app) => {
  app.use("/api/auth", auth);
  app.use("/api/roles", role);
  app.use("/api/grouproles", groupRole);
  app.use("/api/users", user);
  app.use("/api/categories", category);
  app.use("/api/brands", brand);
  app.use("/api/products", product);
  app.use("/api/variants", variant);
  app.use("/api/ratings", rating);
  app.use("/api/comments", comment);
  app.use("/api/discounts", discount);
  app.use("/api/orders", order);
  app.use("/api/sizes", size);
  app.use("/api/colors", color);
  app.use("/api/colors", color);
  app.use("/api/carts", cart);
  app.use("/api/addresses", address);
};
module.exports = router;
